{
 "title": "Cesium Clock Data",
 "description": "Monitors 5071a cesium clock for end-of-life indicators",
 "time": { "from": "now-3w", "to": "now" },
 "refresh": "1h",
 "templating": {
  "list": [
   {
    "name": "measurement1",
    "label": "Measurement 1",
    "query": "[Thermometer], [+5V  supply], [-12V supply], [+12V supply], [uP Clock PLL], [87MHz PLL], [DRO Tuning], [SAW Tuning], [Mass spec], [HW Ionizer], [Ion Pump], [Osc. Oven], [CBT Oven Err], [CBT Oven], [Signal Gain], [E-multiplier], [C-field curr], [Zeeman Freq], [RF amplitude 2], [RF amplitude 1], [Osc. control], [Freq Offset], [Log status], [Power source], [Status summary], [CBT ID], [EUT_MJD], [EUT_IDN], [NOW_UNIX], [NOW_MJD], [NOW_LOC], [NOW_UTC]"
   },
   {
    "name": "measurement2",
    "label": "Measurement 2",
    "query": "[Thermometer], [+5V  supply], [-12V supply], [+12V supply], [uP Clock PLL], [87MHz PLL], [DRO Tuning], [SAW Tuning], [Mass spec], [HW Ionizer], [Ion Pump], [Osc. Oven], [CBT Oven Err], [CBT Oven], [Signal Gain], [E-multiplier], [C-field curr], [Zeeman Freq], [RF amplitude 2], [RF amplitude 1], [Osc. control], [Freq Offset], [Log status], [Power source], [Status summary], [CBT ID], [EUT_MJD], [EUT_IDN], [NOW_UNIX], [NOW_MJD], [NOW_LOC], [NOW_UTC]"
   }
  ]
 },
 "panels": [
  {
   "title": "Electron Multiplier Voltage (V)",
   "type": "timeseries",
   "description": "A sudden jump in the electron multiplier voltage may indicate that the CBT is entering its end-of-life period. This jump will be around 2 to 50 days prior to failure. After this, it will increase until it hits a maximum value of 2553 V.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT CAST([NOW_UNIX] AS INT) as time, CAST(TRIM([E-multiplier], 'VCuA% ') AS REAL) as 'Electron Multiplier'\nfrom data\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "rawQueryText": "SELECT CAST([NOW_UNIX] AS INT) as time, CAST(TRIM([E-multiplier], 'VCuA% ') AS REAL) as 'Electron Multiplier'\nfrom data\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "RF Amplitude 2 (% of Maximum)",
   "type": "timeseries",
   "description": "This may show an average decrease up to 25 days prior to CBT failure. It will also vary much more during the end-of-life period.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT CAST([NOW_UNIX] AS INT) as time, CAST(TRIM([RF amplitude 2], 'VCuA% ') AS REAL) as 'RF Amplitude 2'\nfrom data\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "rawQueryText": "SELECT CAST([NOW_UNIX] AS INT) as time, CAST(TRIM([RF amplitude 2], 'VCuA% ') AS REAL) as 'RF Amplitude 2'\nfrom data\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Ion Pump Current (µA)",
   "type": "timeseries",
   "description": "The ion pump current should have a low startup value (typically near 0.0) and remain constant. Some devices, however, work quite well with constant values of 10, 20, or higher (USNO has one device working well with an ion pump current of 36.0 microamps). This value is one of those \"personality\" characteristics of each device. A high current value can indicate a vacuum or electrical leak, that the tube has been off for a long period, or that the tube is contaminated. A current greater than 50 microamps will cause shutdown.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "queryText": "SELECT CAST([NOW_UNIX] AS INT) as time, CAST(TRIM([Ion Pump], 'VCuA% ') AS REAL) as 'Ion Pump Current'\nfrom data\nWHERE time >= 1686677400000 / 1000 and time < 1687459895057 / 1000",
     "rawQueryText": "SELECT CAST([NOW_UNIX] AS INT) as time, CAST(TRIM([Ion Pump], 'VCuA% ') AS REAL) as 'Ion Pump Current'\nfrom data\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Oscillator Control Percentage (%)",
   "type": "timeseries",
   "description": "Oscillator control percentage is a very important value to monitor. The value can be positive or negative and is very characteristic of the device. One standard may have an oscillator control value of -8.6% and another standard may have a value of -43.1%. Neither of these values \nalone means that the clock is performing (or will perform) poorly. A variation in the value may suggest a future failure. What is important about the oscillator control percentage for performance is its frequency and amount of change. For example, USNO has had at least two standards that exhibit a phase or rate change that was coincident with a change in its oscillator control percentage. Such an occurrence may be due to the standard experiencing an environmental change (temperature and/or humidity), a Cesium Beam Tube (CBT) change, or a CBT controller board change, or it may be a precursor to a failure.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "queryText": "SELECT CAST([NOW_UNIX] AS INT) as time, CAST(TRIM([Osc. control], 'VCuA% ') AS REAL) as 'Oscillator Control Percentage'\nfrom data\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "rawQueryText": "SELECT CAST([NOW_UNIX] AS INT) as time, CAST(TRIM([Osc. control], 'VCuA% ') AS REAL) as 'Oscillator Control Percentage'\nfrom data\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Signal Gain Percentage (%)",
   "type": "timeseries",
   "description": "The signal gain percentage should be constant at 14.4% as long as EMV is below maximum of 2553 V. It will quickly rise to 100% after the EMV has hit the maximum. Although signal gain percentage does show when the CBT has failed, it will not show any signs beforehand.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "queryText": "SELECT CAST([NOW_UNIX] AS INT) as time, CAST(TRIM([Signal Gain], 'VCuA% ') AS REAL) as 'Signal Gain Percentage'\nfrom data\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "rawQueryText": "SELECT CAST([NOW_UNIX] AS INT) as time, CAST(TRIM([Signal Gain], 'VCuA% ') AS REAL) as 'Signal Gain Percentage'\nfrom data\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Internal Temperature (°C)",
   "type": "timeseries",
   "description": "The internal temperature should typically range from 35 to 45 degrees Celsius. It will change as the standard's environment changes.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "queryText": "SELECT CAST([NOW_UNIX] AS INT) as time, CAST(TRIM([Thermometer], 'VCuA% ') AS REAL) as 'Internal Temperature'\nfrom data\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "rawQueryText": "SELECT CAST([NOW_UNIX] AS INT) as time, CAST(TRIM([Thermometer], 'VCuA% ') AS REAL) as 'Internal Temperature'\nfrom data\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Measurement 1",
   "type": "timeseries",
   "description": "Use the \"Measurement 1\" variable at the top of the dashboard to change which measurement is graphed here.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "queryText": "SELECT CAST([NOW_UNIX] AS INT) as time, CAST(TRIM($measurement1, 'VCuA%MJD ') as REAL) as $measurement1\nfrom data\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "rawQueryText": "SELECT CAST([NOW_UNIX] AS INT) as time, CAST(TRIM($measurement1, 'VCuA%MJD ') as REAL) as $measurement1\nfrom data\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Measurement 2",
   "type": "timeseries",
   "description": "Use the \"Measurement 2\" variable at the top of the dashboard to change which measurement is graphed here.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "queryText": "SELECT CAST([NOW_UNIX] AS INT) as time, CAST(TRIM($measurement2, 'VCuA%MJD ') AS REAL) as $measurement2\nfrom data\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "rawQueryText": "SELECT CAST([NOW_UNIX] AS INT) as time, CAST(TRIM($measurement2, 'VCuA%MJD ') AS REAL) as $measurement2\nfrom data\nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}